### ISSUE TITLE
[PE-D] Does not support events that lasted overnight

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-1/tp#208] opened 2022-04-01 17:29 UTC
![image.png](https://raw.githubusercontent.com/vishandi/ped/master/files/73a85b65-5bd7-4982-bbc2-2278fd5eb3e8.png)

As the END_TIME doesn't have date, it cannot support overnight events, like new year party.

![image.png](https://raw.githubusercontent.com/vishandi/ped/master/files/8596cb6b-ec7d-4854-bcf8-85408e7799f6.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: vishandi/ped#9

**Comment by ChanWeiJie** [comment] 2022-04-02 07:48
Duplicate of #205.
Thank you for the feature suggestion. We will take this into consideration after v1.4.

**Closed by ChanWeiJie** 2022-04-02 07:48 UTC
Labels: feature suggestions
